import Head from 'next/head';

const Header = () => (
  <div>
    <Head>
      <title>JammyLand</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <p>Hello world!</p>
  </div>
);

export default Header;